import Head from 'next/head'
import { useState } from 'react'

export default function Home() {
  // name
  const [name, setName] = useState("")
  // email
  const [email, setEmail] = useState("")
  // phone
  const [phone, setPhone] = useState("")
  // message
  const [message, setMessage] = useState("")

  const handleSubmit = async (e) => {
    e.preventDefault();

    const form = {
      name,
      message,
      phone,
      email
    }

    const response = await fetch('/api/submit',{
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(form)
    });

    const content = await response.json();
    
    console.log(content)
    //alert(content.data);

    setMessage('');
    setName('');
    setEmail('');
    setPhone('');
  }


  return (
    <div>
      <Head>
        <title>Google Form Sheet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex items-center justify-center">
        <form onSubmit={handleSubmit} className="bg-white flex rounded-lg w-1/2">
          <div className="flex-1 text-gray-700 p-20">
            <h1 className="text-3xl pb-2 font-bold">Input Form GoogleSheet</h1>
            <p className="text-lg text-gray-500">
              Input Form otomatis akan terinput ke googlesheet Api
              menggunakan Nextjs dan tailwindcss
            </p>
            <div className="mt-6">
              {/* name input field */}
              <div className="pb-4">
                <label className="block font-bold text-sm pb-2" htmlFor="name">Name</label>
                <input value={name} onChange={e => setName(e.target.value)} className="border-2 p-2 rounded-md w-full border-teal-400" type="text" name="name" placeholder="Enter Your Name" />
              </div>
              {/* email input field */}
              <div className="pb-4">
                <label className="block font-bold text-sm pb-2" htmlFor="email">Email</label>
                <input value={email} onChange={e => setEmail(e.target.value)} className="border-2 p-2 rounded-md w-full border-teal-400" type="email" name="email" placeholder="Enter Your email" />
              </div>
              {/* Phone input field */}
              <div className="pb-4">
                <label className="block font-bold text-sm pb-2" htmlFor="phone">Phone</label>
                <input value={phone} onChange={e => setPhone(e.target.value)} className="border-2 p-2 rounded-md w-full border-teal-400" type="tel" name="phone" placeholder="Enter Your Phone Number" />
              </div>
              {/* message input field */}
              <div className="pb-4">
                <label className="block font-bold text-sm pb-2" htmlFor="message">Message</label>
                <textarea value={message} onChange={e => setMessage(e.target.value)} className="border-2 p-2 rounded-md w-full border-teal-400" name="message" placeholder="Enter Your Message" />
              </div>
              <button type="submit" className="bg-teal-500 text-sm text-white py-3 mt-6 rounded-lg w-full">Start Make Form</button>
            </div>
          </div>
        </form>
      </main>
    </div>
  )
}
